[feature/profile] Create page
kredo-school/14th_explore_ease pull request #30
Opened 2023-11-11 10:02 UTC by sumosumo727

2023-11-13 10:40 UTC, Ditzler01 submitted a review, later dismissed

2023-11-13 12:33 UTC, Ditzler01 commented on routes/web.php
> +Route::get('/profile/reservation', [App\Http\Controllers\HomeController::class, 'profileReservation'])->name('profile.reservation');Route::get('/profile/review', [App\Http\Controllers\HomeController:
Route::get('/profile/review', [App\Http\Controllers\HomeController::class, 'profileReview'])->name('profile.review');
move this to next line

2023-11-15 13:20 UTC, kredo-school requested changes, later dismissed

2023-11-15 13:20 UTC, kredo-school commented on resources/js/textlimit.js
> +$(function() {
if this is to keep the number of lines whatever screen size you are in, you can just use css ellipsis for this
here's an example on how to do it https://stackoverflow.com/questions/5269713/css-ellipsis-on-second-line

2023-11-18 02:35 UTC, Ditzler01 approved these changes

2023-11-18 02:36 UTC, merged