Feature/profile bookmark
kredo-school/14th_explore_ease pull request #31
Opened 2023-11-13 11:13 UTC by kayo-24

I made the bookmark page.

2023-11-13 12:37 UTC, Ditzler01 commented on resources/views/users/bookmark.blade.php
> +
Let's use how laravel 10 import local css. Please take a look on these.
![image](https://github.com/kredo-school/14th_explore_ease/assets/71181685/1f4f08b2-0185-4f6b-8841-45ba6705ba2c)

2023-11-15 12:03 UTC, kredo-school approved these changes

2023-11-15 12:04 UTC, kredo-school requested changes
please fix conflict

2023-11-15 12:12 UTC, kredo-school approved these changes

2023-11-15 12:12 UTC, merged